### ISSUE TITLE
[S1 - PBI03] Membuat halaman tambah pekerjaan

### ISSUE THREAD

**Issue by ainirhmdn** [SI-RPL-2022/SI4301_F_NaKer#1]
Sebagai Pemberi kerja, saya ingin membuat pekerjaan sehingga saya mendapatkan pekerja yang kompeten sesuai dengan kebutuhan

mockup
![image](https://user-images.githubusercontent.com/92175821/164416443-c45de821-a222-4337-9934-020f044da733.png)

**Comment by ainirhmdn** [comment]
<img width="504" alt="image" src="https://user-images.githubusercontent.com/92175821/162164023-1a320437-425d-425d-aab6-e8cb8538c546.png">
S1 - PBI3
Diatas adalah contoh mockup dashboard

**Comment by tienfkusumasari** [comment]
done (SP2)
