### ISSUE TITLE
[S2 - PBI15] Membuat halaman memberi pembayaran

### ISSUE THREAD

**Issue by ericdallan** [SI-RPL-2022/SI4301_F_NaKer#10]
Sebagai Pemberi kerja, saya ingin memberi pembayaran sehingga saya memberikan pembayaran atas jasa pekerja sesuai dengan pekerjaan yang telah dilakukan.

Navigasi : Setelah melakukan seleksi terhadap freelancer, pemberi kerja dapat melakukan pembayaran dengan mencamtumkan bukti pembayaran. Pembayaran yang telah dilakukan kemudian akan masuk kedalam bagian riwayat pembayaran. 

![image](https://user-images.githubusercontent.com/92176975/164423896-e5040adc-78a8-42e6-9c4e-5244f475cec4.png)

**Comment by tienfkusumasari** [comment]
belum ada logic baru tampilan

**Comment by tienfkusumasari** [comment]
done (SP3)
