### ISSUE TITLE
[S2 - PBI13] Membuat halaman menerima pembayaran

### ISSUE THREAD

**Issue by anggraexena** [SI-RPL-2022/SI4301_F_NaKer#11]
Sebagai Freelancer, saya ingin menerima pembayaran sehingga saya mendapatkan penghasilan dari pekerjaan yang saya lakukan
**Navigasi** : Login sebagai freelancer, kunjungi halaman menerima pembayaran, lalu pilih 'Selesai' jika freelancer sudah menerima pembayaran, dan download bukti pembayaran dalam bentuk pdf

Mockup
![Halaman Menerima Pembayaran](https://user-images.githubusercontent.com/28784747/175850025-fbc92ae9-c93d-42c7-8f72-468f3a2a5579.png)

**Comment by tienfkusumasari** [comment]
tambahkan alur dan navigasi di issue nya 
masih error....

**Comment by anggraexena** [comment]
karena fitur status seleksi belum ada, jadi cara manualnya :
- freelancer apply pekerjaan
- edit atribut status di tabel my_jobs jadi "Selesai"
- insert/tambahkan manual di tabel pembayarans (id, gaji disesuaikan dengan my_jobs)

**Comment by tienfkusumasari** [comment]
done (SP3)
