### ISSUE TITLE
[S2 - PBI09] Membuat halaman melamar pekerjaan

### ISSUE THREAD

**Issue by anggraexena** [SI-RPL-2022/SI4301_F_NaKer#12]
User Stories : Sebagai Freelancer, saya ingin melamar pekerjaan saya dapat memiliki pekerjaan sesuai dengan kemampuan yang dimiliki

Navigasi : Freelancer harus login terlebih dahulu jika memiliki akun, atau registrasi jika belum memiliki akun. Lalu pilih menu pekerjaan, pada menu pekerjaan dapat melihat pekerjaan yang tersedia dan dapat klik tombol mengapply atau melamar pekerjaan, lalu pada halaman berikutnya isi file-file yang dibutuhkan seperti CV, Portofolio dan sertifikat lainnya. jika sudah selesai maka klik apply / lamar

![Halaman Melamar Pekerjaan (baru)](https://user-images.githubusercontent.com/28784747/168232189-8e3a566d-ef04-42ea-92e3-4c6c29d49277.png)

**Comment by tienfkusumasari** [comment]
tambahkan alur dan navigasi di issue 
hasil test dilihat di MySQL (done)
