### ISSUE TITLE
[S2 -PBI10] Membuat halaman input status seleksi

### ISSUE THREAD

**Issue by notepeds** [SI-RPL-2022/SI4301_F_NaKer#13]
Sebagai Pemberi kerja, saya ingin menginput status seleksi sehingga saya dapat mengetahui sejauh mana proses seleksi yang saya buat

Navigasi : Setelah freelancer melakukan  apply pekerjaan, pemberi kerja dapat mengubah status seleksi dari freelancer yang melakukan apply dari pekerjaan yang diberikan pemberi kerja. 

Note : Jika freelancer tersebut terpilih, maka akan muncul dibagian pembayaran dan status seleksi dibagian freelancer akan berubah menjadi "Terpilih". Sedangkan jika freelancer tersebut tertolak, maka tidak akan muncul dibagian pembayaran dan status seleksi dibagian freelancer akan berubah menjadi "Tertolak".
![Halaman Input Status Seleksi1](https://user-images.githubusercontent.com/92135758/164424551-62cc3733-cc9f-4fb5-974a-b6d4ab9a8dc1.png)

**Comment by tienfkusumasari** [comment]
baru tampilan

**Comment by tienfkusumasari** [comment]
baru tampilan di SP2

**Comment by tienfkusumasari** [comment]
tidak di beri update (SP3).....
