### ISSUE TITLE
[S2 - PBI11] Membuat halaman detail pekerjaan

### ISSUE THREAD

**Issue by notepeds** [SI-RPL-2022/SI4301_F_NaKer#14]
Sebagai pencari kerja, saya ingin melihat detail pekerjaan sehingga saya mengetahui apa yang dibutuhkan dan harus dilakukan di dalam pekerjaan tersebut
Alur: masuk ke halaman utama Perusahaan, kemudian klik menu Pekerjaan pada navbar, kemudian klik icon pensil pada daftar pekerjaan yang ingin dipilih
![Halaman Detail Pekerjaan1](https://user-images.githubusercontent.com/92135758/164424985-2674f642-6092-40f3-8dfe-2ce0fb933533.png)

**Comment by tienfkusumasari** [comment]
baru tampilan (SP2)

**Comment by tienfkusumasari** [comment]
close SP3
