### ISSUE TITLE
[S2 -PBI14] Membuat halaman video training

### ISSUE THREAD

**Issue by ainirhmdn** [SI-RPL-2022/SI4301_F_NaKer#15]
Sebagai Freelancer, saya ingin melihat video training sehingga saya dapat meningkatkan kemampuan yang dimiliki melalui video training

mockup
<img width="542" alt="image" src="https://user-images.githubusercontent.com/92175821/171591731-7c900878-5981-482e-86bd-7df3c7b92288.png">

**Comment by tienfkusumasari** [comment]
done
