### ISSUE TITLE
[S3 -PBI18] Membuat halaman depan (homepage)

### ISSUE THREAD

**Issue by ainirhmdn** [SI-RPL-2022/SI4301_F_NaKer#17]
Sebagai Pemberi kerja,  Admin , dan Freelancer , saya ingin melihat dashboard sehingga saya dapat melihat overview mengenai data-data dan fakta dari website ini

navigasi : setelah register dan melakukan login, maka akan langsung ke direct ke halaman dashboard

mockup
<img width="948" alt="image" src="https://user-images.githubusercontent.com/92175821/174282711-88f5e188-4142-4100-b0c9-c9d770a70933.png">

**Comment by tienfkusumasari** [comment]
done (SP3)
