### ISSUE TITLE
[S3 -PBI17] Membuat fitur edit Pekerjaan

### ISSUE THREAD

**Issue by ericdallan** [SI-RPL-2022/SI4301_F_NaKer#18]
Sebagai Pemberi kerja, Saya dapat memperbarui deskripsi dari pekerjaan yang sedang membutuhkan sumber daya manusia atau freelancer.

navigasi : pada halaman dashboard, klik pada tab pekerjaan (pemberi kerja) , maka akan tampil ke halaman daftar-daftar pekerjaan, lalu klik ikon edit pekerjaan maka akan tampil pop up edit pekerjaan

<img width="530" alt="image" src="https://user-images.githubusercontent.com/92175821/174295168-306b68c8-1486-4f55-b6bc-aea1eb98ac5d.png">

**Comment by tienfkusumasari** [comment]
done (SP3)
