### ISSUE TITLE
[S3 - PBI16] Membuat halaman status seleksi

### ISSUE THREAD

**Issue by notepeds** [SI-RPL-2022/SI4301_F_NaKer#19]
![Halaman Fitur Edit Pekerjaan1](https://user-images.githubusercontent.com/92135758/164488339-0b2e1e16-81fa-4ef9-8542-b2373a4e032b.png)
Sebagai Freelancer, saya ingin melihat status seleksi sehingga saya dapat mengetahui apakah saya diterima atau ditolak untuk pekerjaan tersebut

Navigasi : Setelah melakukan apply pekerjaan, freelancer mampu untuk melihat status seleksi apakah dia terpilih ("Terpilih") atau tertolak ("Tertolak") untuk pekerjaan tersebut. Selain itu dibagian status seleksi, freelancer mampu untuk menghapus seleksi yang tertolak ("Tertolak").

Note : Freelancer tidak mampu untuk menghapus seleksi yang telah selesai. Dikarenakan id dari seleksi tersebut digunakan untuk dalam pembayaran.

**Comment by tienfkusumasari** [comment]
UPDAE judl mestinya menampilkan halaman seleksi (done SP3)
