### ISSUE TITLE
[S3 - PBI20] Membuat halaman riwayat pembayaran

### ISSUE THREAD

**Issue by ericdallan** [SI-RPL-2022/SI4301_F_NaKer#20]
Sebagai Pemberi karaya, saya ingin melihat riwayat pembayaran sehingga saya dapat mengetahui pembayaran apa saja yang telah saya lakukan.

Navigasi : Setelah memberi pembayaran terhadap freelancer, pemberi kerja dapat melihat riwayat pembayaran dengan membuka halam pembayaran melakukan klik pada button riwayat pembayaran.

Note : Setelah melakukan pembayaran, pemberi kerja bisa melihat dari detail pembayaran tersebut. Status dalam detail pembayaran masih "Belum Bayar" karena menunggu konfirmasi pembayaran dari freelancer. Jika sudah di konfirmasi oleh freelancer, maka status tersebut berubah menjadi "Sudah Bayar".

Mockup : 
![image](https://user-images.githubusercontent.com/92176975/175877039-1b241b8e-85d6-43f6-add6-16f0ee6cce10.png)

**Comment by tienfkusumasari** [comment]
done (SP3)
