### ISSUE TITLE
[S1 - PBI05] Membuat halaman profile

### ISSUE THREAD

**Issue by notepeds** [SI-RPL-2022/SI4301_F_NaKer#3]
Sebagai Pencari Kerja, saya ingin melihat profile sehingga saya dapat memastikan
apakah data diri yang saya masukan sudah sesuai atau belum
Alur: masuk ke halaman utama freelancer, kemudian klik icon orang, akan muncul dropdown, kemudian pilih profil

![Profile](https://user-images.githubusercontent.com/92135758/163946968-1d3a8865-128e-4dac-935a-1af86560bf35.png)

**Comment by tienfkusumasari** [comment]
done
