### ISSUE TITLE
[S1 - PBI04] Membuat halaman mencari kerja

### ISSUE THREAD

**Issue by anggraexena** [SI-RPL-2022/SI4301_F_NaKer#4]
Sebagai Penerima Kerja, Saya ingin melihat daftar pekerjaan, sehingga Saya dapat mengetahui pekerjaan yang sekiranya sesuai dengan kompetensi yang dimiliki, dengan bantuan pencarian kerja pada search bar dan juga menampilkan pekerjaan berdasarkan kategori

note tambahan : pada fitur ini dibuatkan front-end halaman mencari kerja yang berisi list pekerjaan (read), juga terdapat input pencarian (read) dan menampilkan kategori pekerjaan (read)
Alur: masuk ke halaman utama untuk freelancer, kemudian pilih menu pekerjaan pada navbar, kemudian akan muncul pilihan-pilihan pekerjaan kosong, pilih dengan klik tombol apply

Mockup 

![Halaman Mencari Kerja (Penerima kerja) baru](https://user-images.githubusercontent.com/28784747/168402409-2b7df512-d8db-4316-9fe6-341f287c192b.png)

**Comment by tienfkusumasari** [comment]
done
