### ISSUE TITLE
[S1 - PBI02] Membuat Halaman Login

### ISSUE THREAD

**Issue by ericdallan** [SI-RPL-2022/SI4301_F_NaKer#5]
User Stories : Sebagai Freelancer dan Pemberi Kerja, saya ingin melakukan login ke dalam website NaKer sehingga saya dapat mengeksplorasi website lebih jauh.
Alur: masuk ke halaman utama, kemudian klik menu login pada navbar, pilih freelancer apabila ingin masuk sebagai pencari kerja, atau pilih perusahaan apabila ingin masuk sebagai perusahaan

![image](https://user-images.githubusercontent.com/28784747/171639506-024b054f-fddc-4a23-89d9-a45b456626ba.png)

**Comment by ericdallan** [comment]
![image](https://user-images.githubusercontent.com/92176975/163727416-902e6661-a4f2-41fe-862b-c95877d611df.png)

**Comment by tienfkusumasari** [comment]
done

**Comment by tienfkusumasari** [comment]
tambahkan pilihan sebgai freelancer atau pemberi kerja pada halaman mockup nya
