### ISSUE TITLE
[S1 - PBI01] Membuat Halaman Registrasi

### ISSUE THREAD

**Issue by ericdallan** [SI-RPL-2022/SI4301_F_NaKer#6]
Sebagai Freelancer dan Pemberi Kerja, saya ingin melakukan registrasi ke dalam website NaKer sehingga saya dapat memiliki akun NaKer dan dapat mengakses seluruh fitur yang terdapat di website Naker.

Pemberi Kerja
![Halaman Registrasi Pemberi Kerja](https://user-images.githubusercontent.com/28784747/168403632-86235cb4-375c-419a-a691-472700bdda88.png)

Penerima Kerja
![Halaman Registrasi Penerima](https://user-images.githubusercontent.com/28784747/168403634-407b45f6-1cc8-48b1-806e-ce89ddd20c2d.png)

**Comment by ericdallan** [comment]
![image](https://user-images.githubusercontent.com/92176975/163727485-9ca3a80e-92ec-4332-9457-b09b26b3e382.png)
S1 - PB01 Mockup Halaman Registrasi

**Comment by tienfkusumasari** [comment]
done
