### ISSUE TITLE
[S2 - PBI12] Membuat halaman upload video training

### ISSUE THREAD

**Issue by ainirhmdn** [SI-RPL-2022/SI4301_F_NaKer#9]
Sebagai Admin, saya ingin membuat video training sehingga membantu freelancer dalam meningkatkan kemampuan yang dimilikinya

video yang akan di upload adalah berbentk link dari youtube, adapun tahapan dari upload nya adalah judul video, deskripsi, link dan durasi video tersebut.

Mockup
<img width="960" alt="image" src="https://user-images.githubusercontent.com/92175821/171575945-01871018-8cab-48cf-bab4-78a75a63e607.png">

**Comment by tienfkusumasari** [comment]
done
